model_path: "yolov8m.pt"
detect_classes: [0, 2, 24, 28, 62, 63, 72]  # person, backpack, suitcase, tv, laptop, refrigerator
track_thresh: 0.3
match_thresh: 0.85
track_buffer: 120
aspect_ratio_thresh: 3.0
min_box_area: 10